name = "COST"
uuid = "2f4fe677-3870-42d8-b5e0-8b567d81bf25"
version = "0.1.0"
authors = ["phajy <andy.young@bristol.ac.uk>"]

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Documenter = "1.16.0"

[workspace]
projects = ["docs"]

