name = "COST"
uuid = "2f4fe677-3870-42d8-b5e0-8b567d81bf25"
version = "0.1.0"
authors = ["phajy <andy.young@bristol.ac.uk>"]

[workspace]
projects = ["docs"]

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Gradus = "c5b7b928-ea15-451c-ad6f-a331a0f3e4b7"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Documenter = "1.16.0"
Gradus = "0.4.30"
Latexify = "0.16.10"
Plots = "1.41.2"
StaticArrays = "1.9.16"
Symbolics = "7.0.2"
